trigger:
  branches:
    include:
    - master
    - hotfix/*
    - release/*
    - dev
  paths:
    include:
    - sdk/storage/

pr:
  branches:
    include:
    - master
    - feature/*
    - hotfix/*
    - release/*
    - dev
  paths:
    include:
    - sdk/storage/

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: storage
    Artifacts:
    - name: AzureStorageBlob
      safeName: AzureStorageBlob