trigger:
  branches:
    include:
    - master
    - hotfix/*
    - release/*
    - dev
  paths:
    include:
    - sdk/core/
pr:
  branches:
    include:
    - master
    - feature/*
    - hotfix/*
    - release/*
    - dev
  paths:
    include:
    - sdk/core/
extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: core
    Artifacts:
    - name: AzureCore
      safeName: azurecore
